
["Beyond Planets Core - Moon Ore Config"]

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Copper Ore Config"]
		#Should Moon Copper Ore Height Top.
		#Default = 32 (number)
		"Moon Copper Ore Height Top" = 32
		#Should Moon Copper Ore Height Bottom.
		#Default = -32 (number)
		"Moon Copper Ore Height Bottom" = -32
		#Should Moon Copper Ore Vein Size.
		#Default = 8 (number)
		"Moon Copper Ore Vein Size" = 8

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Lead Ore Config"]
		#Should Moon Lead Height Top.
		#Default = 56 (number)
		"Moon Lead Ore Height Top" = 56
		#Should Moon Lead Height Bottom.
		#Default = -34 (number)
		"Moon Lead Ore Height Bottom" = -24
		#Should Moon Lead Ore Vein Size.
		#Default = 8 (number)
		"Moon Lead Ore Vein Size" = 10

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Tin Ore Config"]
		#Should Moon Tin Height Top.
		#Default = 80 (number)
		"Moon Tin Ore Height Top" = 80
		#Should Moon Tin Ore Height Bottom.
		#Default = -80 (number)
		"Moon Tin Ore Height Bottom" = -80
		#Should Moon Tin Ore Vein Size.
		#Default = 8 (number)
		"Moon Tin Ore Vein Size" = 7

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Uranium Ore Config"]
		#Should Moon Uranium Height Top.
		#Default = 80 (number)
		"Moon Uranium Ore Height Top" = 80
		#Should Moon Uranium Ore Height Bottom.
		#Default = -80 (number)
		"Moon Uranium Ore Height Bottom" = -80
		#Should Moon Uranium Ore Vein Size.
		#Default = 8 (number)
		"Moon Uranium Ore Vein Size" = 6

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Zinc Ore Config"]
		#Should Moon Zinc Ore spawn.
		#Default = 80 (number)
		"Moon Zinc Ore Height Top" = 80
		#Should Moon Zinc Ore Height Bottom.
		#Default = -80 (number)
		"Moon Zinc Ore Height Bottom" = -80
		#Should Moon Zinc Ore Vein Size.
		#Default = 8 (number)
		"Moon Zinc Ore Vein Size" = 6

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Cobalt Ore Config"]
		#Should Moon Cobalt Ore spawn.
		#Default = 80 (number)
		"Moon Cobalt Ore Height Top" = 80
		#Should Moon Cobalt Ore Height Bottom.
		#Default = -80 (number)
		"Moon Cobalt Ore Height Bottom" = -80
		#Should Moon Cobalt Ore Vein Size.
		#Default = 8 (number)
		"Moon Cobalt Ore Vein Size" = 6

	["Beyond Planets Core - Moon Ore Config"."Beyond Planets Core - Moon Coal Ore Config"]
		#Should Moon Coal Ore spawn.
		#Default = 80 (number)
		"Moon Coal Ore Height Top" = 80
		#Should Moon Coal Ore Height Bottom.
		#Default = -80 (number)
		"Moon Coal Ore Height Bottom" = -80
		#Should Moon Coal Ore Vein Size.
		#Default = 8 (number)
		"Moon Coal Ore Vein Size" = 6

