
["Beyond Planets Core - Mercury Ore Config"]

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Copper Ore Config"]
		#Should Mercury Copper Ore Height Top.
		#Default = 32 (number)
		"Mercury Copper Ore Height Top" = 32
		#Should Mercury Copper Ore Height Bottom.
		#Default = -32 (number)
		"Mercury Copper Ore Height Bottom" = -32
		#Should Mercury Copper Ore Vein Size.
		#Default = 8 (number)
		"Mercury Copper Ore Vein Size" = 8

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Lead Ore Config"]
		#Should Mercury Lead Height Top.
		#Default = 56 (number)
		"Mercury Lead Ore Height Top" = 56
		#Should Mercury Lead Height Bottom.
		#Default = -34 (number)
		"Mercury Lead Ore Height Bottom" = -24
		#Should Mercury Lead Ore Vein Size.
		#Default = 8 (number)
		"Mercury Lead Ore Vein Size" = 10

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Tin Ore Config"]
		#Should Mercury Tin Height Top.
		#Default = 80 (number)
		"Mercury Tin Ore Height Top" = 80
		#Should Mercury Tin Ore Height Bottom.
		#Default = -80 (number)
		"Mercury Tin Ore Height Bottom" = -80
		#Should Mercury Tin Ore Vein Size.
		#Default = 8 (number)
		"Mercury Tin Ore Vein Size" = 7

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Uranium Ore Config"]
		#Should Mercury Uranium Height Top.
		#Default = 80 (number)
		"Mercury Uranium Ore Height Top" = 80
		#Should Mercury Uranium Ore Height Bottom.
		#Default = -80 (number)
		"Mercury Uranium Ore Height Bottom" = -80
		#Should Mercury Uranium Ore Vein Size.
		#Default = 8 (number)
		"Mercury Uranium Ore Vein Size" = 6

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Zinc Ore Config"]
		#Should Mercury Zinc Ore spawn.
		#Default = 80 (number)
		"Mercury Zinc Ore Height Top" = 80
		#Should Mercury Zinc Ore Height Bottom.
		#Default = -80 (number)
		"Mercury Zinc Ore Height Bottom" = -80
		#Should Mercury Zinc Ore Vein Size.
		#Default = 8 (number)
		"Mercury Zinc Ore Vein Size" = 6

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Cobalt Ore Config"]
		#Should Mercury Cobalt Ore spawn.
		#Default = 80 (number)
		"Mercury Cobalt Ore Height Top" = 80
		#Should Mercury Cobalt Ore Height Bottom.
		#Default = -80 (number)
		"Mercury Cobalt Ore Height Bottom" = -80
		#Should Mercury Cobalt Ore Vein Size.
		#Default = 8 (number)
		"Mercury Cobalt Ore Vein Size" = 6

	["Beyond Planets Core - Mercury Ore Config"."Beyond Planets Core - Mercury Coal Ore Config"]
		#Should Mercury Coal Ore spawn.
		#Default = 80 (number)
		"Mercury Coal Ore Height Top" = 80
		#Should Mercury Coal Ore Height Bottom.
		#Default = -80 (number)
		"Mercury Coal Ore Height Bottom" = -80
		#Should Mercury Coal Ore Vein Size.
		#Default = 8 (number)
		"Mercury Coal Ore Vein Size" = 6

